#!/usr/bin/env bash
set -euo pipefail

MODEL_PATH="${MODEL_PATH:-mistralai/Mistral-7B-v0.3}"
MODELS_ROOT="${MODELS_ROOT:-/models}"
PYTHON_BIN="${PYTHON_BIN:-python}"
LM_EVAL_TASK_PRESET="${LM_EVAL_TASK_PRESET:-extended}"
INCLUDE_LM_EVAL="${INCLUDE_LM_EVAL:-1}"
INCLUDE_C4="${INCLUDE_C4:-1}"
USE_WANDB="${USE_WANDB:-1}"
WANDB_PROJECT="${WANDB_PROJECT:-smartflip}"
WANDB_ENTITY="${WANDB_ENTITY:-}"

KNEE_VALUES=(0.0 0.01 0.02 0.03 0.04 0.05)
MAX_FLIP_VALUES=(0.01 0.02 0.03 0.04 0.05)

echo "==> float_model :: ${MODEL_PATH}"
MODEL_PATH="$MODEL_PATH" MODELS_ROOT="$MODELS_ROOT" PYTHON_BIN="$PYTHON_BIN" LM_EVAL_TASK_PRESET="$LM_EVAL_TASK_PRESET" INCLUDE_LM_EVAL="$INCLUDE_LM_EVAL" INCLUDE_C4="$INCLUDE_C4" USE_WANDB="$USE_WANDB" WANDB_PROJECT="$WANDB_PROJECT" WANDB_ENTITY="$WANDB_ENTITY" bash scripts/bash/run_float_model.sh

echo "==> raw_quantize :: ${MODEL_PATH}"
MODEL_PATH="$MODEL_PATH" MODELS_ROOT="$MODELS_ROOT" PYTHON_BIN="$PYTHON_BIN" LM_EVAL_TASK_PRESET="$LM_EVAL_TASK_PRESET" INCLUDE_LM_EVAL="$INCLUDE_LM_EVAL" INCLUDE_C4="$INCLUDE_C4" USE_WANDB="$USE_WANDB" WANDB_PROJECT="$WANDB_PROJECT" WANDB_ENTITY="$WANDB_ENTITY" bash scripts/bash/run_raw_quantize.sh

for knee in "${KNEE_VALUES[@]}"; do
  for max_flip in "${MAX_FLIP_VALUES[@]}"; do
    echo "==> flip_quantize :: ${MODEL_PATH} :: knee=${knee} :: max_flip=${max_flip}"
    MODEL_PATH="$MODEL_PATH"     MODELS_ROOT="$MODELS_ROOT"     PYTHON_BIN="$PYTHON_BIN"     LM_EVAL_TASK_PRESET="$LM_EVAL_TASK_PRESET"     INCLUDE_LM_EVAL="$INCLUDE_LM_EVAL"     INCLUDE_C4="$INCLUDE_C4"     USE_WANDB="$USE_WANDB"     WANDB_PROJECT="$WANDB_PROJECT"     WANDB_ENTITY="$WANDB_ENTITY"     KNEE_TOLERANCE="$knee"     MAX_FLIP_PERCENT="$max_flip"     bash scripts/bash/run_flip_quantize.sh
  done
done
