#!/usr/bin/env bash
set -euo pipefail

MODEL_PATH="${MODEL_PATH:-meta-llama/Meta-Llama-3-8B}"
MODELS_ROOT="${MODELS_ROOT:-/models}"
PYTHON_BIN="${PYTHON_BIN:-python}"
LM_EVAL_TASK_PRESET="${LM_EVAL_TASK_PRESET:-extended}"
INCLUDE_LM_EVAL="${INCLUDE_LM_EVAL:-1}"
INCLUDE_C4="${INCLUDE_C4:-1}"
USE_WANDB="${USE_WANDB:-1}"
WANDB_PROJECT="${WANDB_PROJECT:-smartflip}"
WANDB_ENTITY="${WANDB_ENTITY:-}"
POST_CORRECTION="${POST_CORRECTION:-bias_correction}"
BIAS_CORRECTION_SAMPLES="${BIAS_CORRECTION_SAMPLES:-4096}"

echo "==> float_model :: ${MODEL_PATH}"
MODEL_PATH="$MODEL_PATH" MODELS_ROOT="$MODELS_ROOT" PYTHON_BIN="$PYTHON_BIN" LM_EVAL_TASK_PRESET="$LM_EVAL_TASK_PRESET" INCLUDE_LM_EVAL="$INCLUDE_LM_EVAL" INCLUDE_C4="$INCLUDE_C4" USE_WANDB="$USE_WANDB" WANDB_PROJECT="$WANDB_PROJECT" WANDB_ENTITY="$WANDB_ENTITY" bash scripts/bash/run_float_model.sh

echo "==> raw_quantize :: ${MODEL_PATH}"
MODEL_PATH="$MODEL_PATH" MODELS_ROOT="$MODELS_ROOT" PYTHON_BIN="$PYTHON_BIN" LM_EVAL_TASK_PRESET="$LM_EVAL_TASK_PRESET" INCLUDE_LM_EVAL="$INCLUDE_LM_EVAL" INCLUDE_C4="$INCLUDE_C4" USE_WANDB="$USE_WANDB" WANDB_PROJECT="$WANDB_PROJECT" WANDB_ENTITY="$WANDB_ENTITY" bash scripts/bash/run_raw_quantize.sh

echo "==> bias_correction :: ${MODEL_PATH} :: samples=${BIAS_CORRECTION_SAMPLES}"
MODEL_PATH="$MODEL_PATH" MODELS_ROOT="$MODELS_ROOT" PYTHON_BIN="$PYTHON_BIN" LM_EVAL_TASK_PRESET="$LM_EVAL_TASK_PRESET" INCLUDE_LM_EVAL="$INCLUDE_LM_EVAL" INCLUDE_C4="$INCLUDE_C4" USE_WANDB="$USE_WANDB" WANDB_PROJECT="$WANDB_PROJECT" WANDB_ENTITY="$WANDB_ENTITY" POST_CORRECTION="$POST_CORRECTION" BIAS_CORRECTION_SAMPLES="$BIAS_CORRECTION_SAMPLES" bash scripts/bash/run_quantize.sh
